# Generated by Django 3.0.7 on 2020-06-13 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'Company Type', 'verbose_name_plural': 'Company Types'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterField(
            model_name='city',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city', to='settings.Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='region', to='settings.Country'),
        ),
    ]
